tracker/apps/task/urls.py
from django.urls import path
from .views import TaskCreateView, TaskDetailView, TaskUpdateView, TaskDeleteView
from . import views


urlpatterns = [
      path('project/<slug:slug>/task/new', TaskCreateView.as_view(), name='task-new'),
      path('task/<int:pk>', TaskDetailView.as_view(), name='task-detail'),
      path('project/<slug:slug>/task/<int:pk>/update', TaskUpdateView.as_view(), name='task-update'),
      path('task/<int:pk>/delete', TaskDeleteView.as_view(), name='task-delete')
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='homepage.html'), name="homepage"),
    path('admin/', admin.site.urls),
    path('', include('tracker.apps.user.urls')),
    path('', include('tracker.apps.project.urls')),
    path('', include('tracker.apps.task.urls')),
    path('', include('tracker.apps.log.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/apps/task/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.shortcuts import reverse
from tracker.apps.project.models import Project


class Comment(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.text


class Task(models.Model):
    FEATURE = 0
    BUG = 1

    NORMAL = 0
    HIGH = 1
    LOW = 2

    TYPE_CHOICES = [
        (FEATURE, 'Feature'),
        (BUG, 'Bug')
    ]

    PRIORITY_CHOICES = [
        (NORMAL, 'Normal'),
        (HIGH, 'High'),
        (LOW, 'Low')
    ]

    topic = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    finish_date = models.DateField()
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)
    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES)
    estimate_time = models.PositiveSmallIntegerField()
    executor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tasks_executor')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False,
                                related_name='tasks_creator')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.topic

    def get_absolute_url(self):
        return reverse('task-detail', kwargs={'pk': self.pk})

tracker/apps/task/forms.py
from django import forms
from .models import Task, Comment


class TaskForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'autocomplete': 'off'}))
    finish_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'autocomplete': 'off'}))

    def __init__(self, *args, **kwargs):
        project = kwargs.pop('project', None)
        super(TaskForm, self).__init__(*args, **kwargs)
        if project:
            self.fields['executor'].queryset = project.users

    class Meta:
        model = Task
        fields = ['topic', 'start_date', 'finish_date', 'type', 'priority', 'estimate_time', 'executor', 'description']

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        finish_date = cleaned_data.get("finish_date")

        if start_date and finish_date and finish_date < start_date:
            raise forms.ValidationError("Finish date should be greater than start date.")


class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, label='')

    class Meta:
        model = Comment
        fields = ['text', 'task', 'user']
        widgets = {
            'task': forms.HiddenInput(),
            'user': forms.HiddenInput()
        }

tracker/apps/task/views.py
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from .models import Task
from tracker.apps.project.models import Project
from django.shortcuts import get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.views.generic.edit import FormMixin
from .forms import TaskForm, CommentForm
from django.db.models import Sum
from django.db.models.functions import Coalesce


class TaskCreateView(PermissionRequiredMixin, CreateView):
    model = Task
    template_name = 'task/task_new.html'
    form_class = TaskForm
    permission_required = 'task.add_task'

    def dispatch(self, request, *args, **kwargs):
        self.project = get_object_or_404(Project, slug=self.kwargs.get('slug', None))
        return super(TaskCreateView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.project = get_object_or_404(Project, slug=self.kwargs.get('slug', None))

        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Task
    template_name = 'task/task_update.html'
    form_class = TaskForm

    def dispatch(self, request, *args, **kwargs):
        self.project = get_object_or_404(Project, slug=self.kwargs.get('slug', None))
        return super(TaskUpdateView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(TaskUpdateView, self).get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs

    def test_func(self):
        return _update_detail_permission(self)


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    model = Task
    permission_required = 'task.delete_task'

    def get_success_url(self):
        return self.request.GET.get('next', '/')


class TaskDetailView(LoginRequiredMixin, UserPassesTestMixin, FormMixin, DetailView):
    model = Task
    context_object_name = 'task'
    form_class = CommentForm
    queryset = Task.objects.prefetch_related('comment_set__user').\
        annotate(spent_time_total=Coalesce(Sum('log__spent_time'), 0))

    def get_context_data(self, **kwargs):
        comment_form = CommentForm(initial={'task': self.object, 'user': self.request.user})
        return super(TaskDetailView, self).get_context_data(comment_form=comment_form, **kwargs)

    def get_success_url(self):
        return reverse('task-detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        return self.form_valid(form) if form.is_valid() else self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(TaskDetailView, self).form_valid(form)

    def test_func(self):
        return _update_detail_permission(self)


def _update_detail_permission(self):
    current_user = self.request.user
    if current_user.groups.filter(name='admin').exists() or current_user.is_superuser:
        return True
    return Project.users.through.objects.filter(user_id=current_user.pk,
                                                project_id=self.get_object().project.pk).exists()

templates/task/task_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block base_title %}{{ task.topic }}{% endblock %}

{% block breadcrumbs %}
    {% breadcrumb "Home" "homepage" %}
    {% breadcrumb "Projects" "projects" %}
    {% breadcrumb task.project.name "project-detail" task.project.slug %}
    {% breadcrumb task.topic "task-detail" task.pk %}
    {% render_breadcrumbs %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="float-right">
                <a href="{% url 'logs' task.pk  %}" class="btn btn-success">Log time</a>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-12">
            <strong>Topic:</strong> {{ task.topic }} <br>
            <strong>Start date</strong> {{ task.start_date|date:'d M Y' }} <br>
            <strong>Finish date</strong> {{ task.finish_date|date:'d M Y' }} <br>
            <strong>Type</strong> {{ task.get_type_display }} <br>
            <strong>Priority</strong> {{ task.get_priority_display }} <br>
            <strong>Estimate time</strong> {{ task.estimate_time }} h <br>
            <strong>Spent time</strong> {{ task.spent_time_total }} h<br>
            <strong>Creator</strong> <a href="{% url 'user-detail' task.creator.pk %}">{{ task.creator.username }}</a> <br>
            <strong>Executor</strong> <a href="{% url 'user-detail' task.executor.pk %}">{{ task.executor.username }}</a> <br>
            <strong>Description:</strong>
            <p>{{ task.description }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <form method="post" class="clearfix mb-3">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <div class="form-group">
                    <input type="submit" class="btn btn-success float-right" value="Add comment">
                </div>
            </form>

            {% for comment in task.comment_set.all %}
                <div class="card mb-3 comment">
                <div class="card-header">
                    <a href="{% url 'user-detail' comment.user.pk %}">{{ comment.user.username }}</a>
                    <div class="date float-right">
                        {{ comment.created_at|date:"d M Y H:i" }}
                    </div>
                </div>
                <div class="card-body">
                    {{ comment.text }}
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
{% endblock content %}

templates/task/task_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
     <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-5">
            <div class="card bg-light">
                <div class="card-header">{% block title %}{% endblock %}</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <input type="submit" class="btn btn-success float-right" value="{% block button_text %}{% endblock %}">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script type="text/javascript">
    let settings = {
            language: 'en',
            dateFormat: 'dd/mm/yyyy',
            position: 'bottom right',
            autoClose: true
        };

        $('#id_start_date').datepicker(settings);
        $('#id_finish_date').datepicker(settings);
    </script>
{% endblock js %}

templates/task/task_new.html
{% extends 'task/task_form.html' %}
{% block base_title %}Create new task{% endblock %}
{% block title %}
    Create new task
{% endblock %}

{% block button_text %}
    Create
{% endblock %}

templates/task/task_update.html
{% extends 'task/task_form.html' %}
{% block base_title %}Update new task{% endblock %}
{% block title %}
    Update task
{% endblock %}

{% block button_text %}
    Update
{% endblock %}