tracker/apps/project/urls.py
from django.urls import path, include
from .views import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectUpdateView, ProjectDeleteView


urlpatterns = [
    path('projects', ProjectListView.as_view(), name='projects'),
    path('project/new', ProjectCreateView.as_view(), name='project-new'),
    path('project/<slug:slug>', ProjectDetailView.as_view(), name='project-detail'),
    path('project/<slug:slug>/update', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<slug:slug>/delete', ProjectDeleteView.as_view(), name='project-delete')
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='homepage.html'), name="homepage"),
    path('admin/', admin.site.urls),
    path('', include('tracker.apps.user.urls')),
    path('', include('tracker.apps.project.urls')),
    path('', include('tracker.apps.task.urls')),
    path('', include('tracker.apps.log.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/apps/project/models.py
from django.db import models
from django.urls import reverse
from tracker.apps.user.models import User


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'slug': self.slug})

tracker/apps/task/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.shortcuts import reverse
from tracker.apps.project.models import Project


class Comment(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.text


class Task(models.Model):
    FEATURE = 0
    BUG = 1

    NORMAL = 0
    HIGH = 1
    LOW = 2

    TYPE_CHOICES = [
        (FEATURE, 'Feature'),
        (BUG, 'Bug')
    ]

    PRIORITY_CHOICES = [
        (NORMAL, 'Normal'),
        (HIGH, 'High'),
        (LOW, 'Low')
    ]

    topic = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    finish_date = models.DateField()
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)
    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES)
    estimate_time = models.PositiveSmallIntegerField()
    executor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tasks_executor')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False,
                                related_name='tasks_creator')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.topic

    def get_absolute_url(self):
        return reverse('task-detail', kwargs={'pk': self.pk})

tracker/apps/project/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Project
from tracker.apps.task.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.views.generic.list import MultipleObjectMixin
from django.urls import reverse_lazy


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    context_object_name = 'projects'
    paginate_by = 15

    def get_queryset(self):
        current_user = self.request.user
        query = Project.objects.prefetch_related('users').order_by('-id')
        if current_user.groups.filter(name='admin').exists() or current_user.is_superuser:
            return query.all()
        return query.filter(users__id=current_user.pk)


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    model = Project
    fields = ['name', 'slug', 'users', 'description']
    template_name = 'project/project_new.html'
    permission_required = 'project.add_project'

    def form_valid(self, form):
        if form.cleaned_data['slug'] == 'new':
            form.add_error('slug', 'Not allowed slug.')
            return self.form_invalid(form)
        return super(ProjectCreateView, self).form_valid(form)


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    model = Project
    fields = ['name', 'slug', 'users', 'description']
    template_name = 'project/project_update.html'
    permission_required = 'project.change_project'

    def form_valid(self, form):
        if form.cleaned_data['slug'] == 'new':
            form.add_error('slug', 'Not allowed slug.')
            return self.form_invalid(form)
        return super(ProjectUpdateView, self).form_valid(form)


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects')
    permission_required = 'project.delete_project'


class ProjectDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'project'
    paginate_by = 15

    def get_context_data(self, **kwargs):
        object_list = Task.objects.prefetch_related('creator', 'executor').order_by('-id').\
            filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list, **kwargs)

    def test_func(self):
        current_user = self.request.user
        if current_user.groups.filter(name='admin').exists() or current_user.is_superuser:
            return True
        return Project.users.through.objects.filter(user_id=current_user.pk, project_id=self.get_object().pk).exists()

templates/project/project_detail.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% block base_title %}{{ project.name }}{% endblock %}

{% block breadcrumbs %}
    {% breadcrumb "Home" "homepage" %}
    {% breadcrumb "Projects" "projects" %}
    {% breadcrumb project.name "project-detail" project.slug %}
    {% render_breadcrumbs %}
{% endblock %}

{% block content %}
    <div class="row mb-2">
        <div class="col-md-12">
            <strong>Name:</strong> {{ project.name }} <br>
            <strong>Users:</strong>
            {% for user in project.users.all %}
                <a href="{% url 'user-detail' user.pk %}">{{ user.username }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
            <br>
            <strong>Description:</strong> {{ project.description|safe }}
        </div>
    </div>
    {% if perms.task.add_task %}
    <div class="row mb-2">
        <div class="col-md-12">
            <div class="float-right">
                <a href="{% url 'task-new' project.slug %}" class="btn btn-primary">New task</a>
            </div>
        </div>
    </div>
    {% endif %}
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Topic</th>
            <th scope="col">Start date</th>
            <th scope="col">Finish date</th>
            <th scope="col">Type</th>
            <th scope="col">Priority</th>
            <th scope="col">Estimate time</th>
            <th scope="col">Executor</th>
            <th scope="col">Creator</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for task in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{% url 'task-detail' task.pk %}">{{ task.topic }}</a>
                </td>
                <td>{{ task.start_date|date:"d M Y" }}</td>
                <td>{{ task.finish_date|date:"d M Y" }}</td>
                <td>{{ task.get_type_display }}</td>
                <td>{{ task.get_priority_display }}</td>
                <td>{{ task.estimate_time }} h</td>
                <td>
                    <a href="{% url 'user-detail' task.executor.pk %}">{{ task.executor.username }}</a>
                </td>
                <td>
                    <a href="{% url 'user-detail' task.creator.pk %}">{{ task.creator.username }}</a>
                </td>
                <td>
                    <div class="float-right">
                        <a href="{% url 'task-update' slug=project.slug pk=task.pk %}" class="text-warning"><i class="fas fa-edit"></i></a>
                        {% if perms.task.delete_task %}
                        <form action="{% url 'task-delete' task.pk %}?next={{ request.path|urlencode }}" method="post" class="delete-form-btn" onsubmit="return confirm('Are You sure You want to delete the task?')">
                            {% csrf_token %}
                            <button type="submit" class="transparent-btn text-danger">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
      <div class="float-right">
        {% include '_pagination.html' %}
    </div>
{% endblock content %}

templates/project/project_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
     <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-5">
            <div class="card bg-light">
                <div class="card-header">{% block title %}{% endblock %}</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <input type="submit" class="btn btn-success float-right" value="{% block button_text %}{% endblock %}">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script type="text/javascript" src="{% static 'admin/js/urlify.js' %}"></script>
    <script type="text/javascript">
        document.getElementById("id_name").onkeyup = function() {
        let e = document.getElementById("id_slug");
        if (!e._changed) {
            e.value = URLify(document.getElementById("id_name").value, 255);
        }
    };

     ClassicEditor
        .create( document.querySelector( '#id_description' ))
        .catch( error => {
            console.error( error );
        } );
    </script>
{% endblock %}

templates/project/project_list.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% block base_title %}Projects{% endblock %}

{% block breadcrumbs %}
    {% breadcrumb "Home" "homepage" %}
    {% breadcrumb "Projects" "projects" %}
    {% render_breadcrumbs %}
{% endblock %}

{% block content %}
    {% if perms.project.add_project %}
    <div class="row mb-2">
        <div class="col-md-12">
            <div class="float-right">
                <a href="{% url 'project-new' %}" class="btn btn-primary">New project</a>
            </div>
        </div>
    </div>
    {% endif %}

    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Users</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for project in projects %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{% url 'project-detail' project.slug %}">
                        {{ project.name }}
                    </a>
                </td>
                <td>
                    {% for user in project.users.all %}
                        <a href="{% url 'user-detail' user.pk %}">{{ user.username }}</a>{%if not forloop.last%},{%endif%}
                    {% endfor %}
                </td>
                <td>
                    <div class="float-right">
                        {% if perms.project.change_project %}
                        <a href="{% url 'project-update' project.slug %}" class="text-warning"><i class="fas fa-edit"></i></a>
                        {% endif %}
                        {% if perms.project.delete_project %}
                        <form action="{% url 'project-delete' project.slug %}" method="post" class="delete-form-btn" onsubmit="return confirm('Are You sure You want to delete the project?')">
                            {% csrf_token %}
                            <button type="submit" class="transparent-btn text-danger">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="float-right">
        {% include '_pagination.html' %}
    </div>
{% endblock content %}

templates/project/project_new.html
{% extends 'project/project_form.html' %}
{% block base_title %}Create new project{% endblock %}

{% block title %}
    Create new project
{% endblock %}

{% block button_text %}
    Create
{% endblock %}

templates/project/project_update.html
{% extends 'project/project_form.html' %}
{% block base_title %}Update new project{% endblock %}

{% block title %}
    Update project
{% endblock %}

{% block button_text %}
    Update
{% endblock %}