tracker/apps/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UserListView, UserCreateView, UserDetailView, UserDeleteView, UserUpdateView, ProfileUpdateView


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users', UserListView.as_view(), name='users'),
    path('user/new', UserCreateView.as_view(), name='user-new'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/delete', UserDeleteView.as_view(), name='user-delete'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user-update'),
    path('profile/', ProfileUpdateView.as_view(), name='profile-update')
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='homepage.html'), name="homepage"),
    path('admin/', admin.site.urls),
    path('', include('tracker.apps.user.urls')),
    path('', include('tracker.apps.project.urls')),
    path('', include('tracker.apps.task.urls')),
    path('', include('tracker.apps.log.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from PIL import Image
from django.conf import settings
from django.contrib.auth.models import Group


class User(AbstractUser):
    email = models.EmailField('email address', blank=False, unique=True)
    birth_date = models.DateField(null=True, blank=True)
    position = models.CharField(max_length=60, blank=True)
    image = models.ImageField(upload_to='avatars', blank=True)
    groups = models.ManyToManyField(Group)

    class Meta:
        permissions = [
            ('view_user_list', 'Can view user list')
        ]

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 200 or img.width > 200:
                size = (200, 200)
                img.thumbnail(size)
                img.save(self.image.path)

    def image_url(self):
        if self.image:
            return self.image.url
        return settings.STATIC_URL + 'core/img/avatars/default.png'

tracker/apps/user/forms.py
from django import forms
from .models import User
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth.password_validation import validate_password


class UserCreateForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'autocomplete': 'off'}), required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'groups', 'birth_date', 'position', 'image']


class UserUpdateForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'autocomplete': 'off'}), required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'groups', 'birth_date', 'position', 'image']


class ProfileForm(forms.ModelForm):
    old_password = forms.CharField(widget=forms.PasswordInput(), required=False)
    password = forms.CharField(widget=forms.PasswordInput(), required=False)
    confirm_password = forms.CharField(widget=forms.PasswordInput(), required=False)
    birth_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'autocomplete': 'off'}), required=False)
    field_order = ['first_name', 'last_name', 'email', 'birth_date', 'position', 'old_password', 'password',
                   'confirm_password', 'image']

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'birth_date', 'position', 'image', 'password']

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        old_password = cleaned_data.get("old_password")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if old_password != '' or password != '' or confirm_password != '':
            if not check_password(old_password, self.instance.password):
                self.add_error('old_password', "Password is not correct")
            if password != confirm_password:
                self.add_error('confirm_password', "Password does not match")
            validate_password(password, user=User)
            cleaned_data['password'] = make_password(password)
        else:
            del cleaned_data['password']

        return cleaned_data

tracker/apps/user/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import User
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from .forms import UserCreateForm, UserUpdateForm, ProfileForm


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    context_object_name = 'users'
    paginate_by = 15
    permission_required = 'user.view_user_list'

    def get_queryset(self):
        return User.objects.all().exclude(id=self.request.user.pk).order_by('-id')


class UserCreateView(PermissionRequiredMixin, CreateView):
    model = User
    template_name = 'user/user_new.html'
    form_class = UserCreateForm
    permission_required = 'user.add_user'


class UserUpdateView(PermissionRequiredMixin, UpdateView):
    model = User
    template_name = 'user/user_update.html'
    form_class = UserUpdateForm
    permission_required = 'user.change_user'


class UserDeleteView(PermissionRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users')
    permission_required = 'user.delete_user'


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = 'user'


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'user/user_profile.html'
    form_class = ProfileForm

    def get_object(self, queryset=None):
        return User.objects.get(pk=self.request.user.pk)

templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block base_title %}Login form{% endblock %}
{% block content %}
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-4">
            <div class="card bg-light">
                <div class="card-header">Login form</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <input type="submit" class="btn btn-success float-right" value="Login">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user/user_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block base_title %}{{ user.username }}{% endblock %}
{% block content %}
     <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-5">
            <div class="card bg-light">
                <div class="card-header"><strong>{{ user.username }}</strong> profile</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col mb-5">
                            <img src="{{ user.image_url }}" alt="profile image">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col font-weight-bold">First name</div>
                        <div class="col">{{ user.first_name }}</div>
                    </div>
                    <div class="row">
                        <div class="col font-weight-bold">Last name</div>
                        <div class="col">{{ user.last_name }}</div>
                    </div>
                    <div class="row">
                        <div class="col font-weight-bold">Email address</div>
                        <div class="col">
                            <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col font-weight-bold">Birth date</div>
                        <div class="col">{{ user.birth_date|date:'d M Y' }}</div>
                    </div>

                    <div class="row">
                        <div class="col font-weight-bold">Position</div>
                        <div class="col">{{ user.position }}</div>
                    </div>

                    <div class="row">
                        <div class="col font-weight-bold">Groups</div>
                        <div class="col">
                            {% for group in user.groups.all %}
                            {{ group }}{%if not forloop.last%},{%endif%}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user/user_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
     <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-5">
            <div class="card bg-light">
                <div class="card-header">{% block title %}{% endblock %}</div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group">
                            <input type="submit" class="btn btn-success float-right" value="{% block button_text %}{% endblock %}">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script type="text/javascript">
    let settings = {
            language: 'en',
            dateFormat: 'dd/mm/yyyy',
            position: 'bottom right',
            autoClose: true
        };

        $('#id_birth_date').datepicker(settings);
    </script>
{% endblock js %}

templates/user/user_list.html
{% extends 'base.html' %}
{% block base_title %}Users list{% endblock %}

{% block content %}
    <div class="row mb-2">
        <div class="col-md-12">
            <div class="float-right">
                <a href="{% url 'user-new' %}" class="btn btn-primary">New user</a>
            </div>
        </div>
    </div>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Position</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{% url 'user-detail' user.pk %}">
                        {{ user.username }}
                    </a>
                </td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.birth_date|date:"d M Y" }}</td>
                <td>{{ user.position }}</td>
                <td>
                    <div class="float-right">
                        <a href="{% url 'user-update' user.pk %}" class="text-warning"><i class="fas fa-edit"></i></a>
                        <form action="{% url 'user-delete' user.pk %}" method="post" class="delete-form-btn" onsubmit="return confirm('Are You sure You want to delete the user?')">
                            {% csrf_token %}
                            <button type="submit" class="transparent-btn text-danger">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="float-right">
        {% include '_pagination.html' %}
    </div>
{% endblock content %}

templates/user/user_new.html
{% extends 'user/user_form.html' %}
{% block base_title %}Create new user{% endblock %}
{% block title %}
    Create new user
{% endblock %}

{% block button_text %}
    Create
{% endblock %}

templates/user/user_profile.html
{% extends 'user/user_form.html' %}
{% block base_title %}Profile{% endblock %}
{% block title %}
    Profile
{% endblock %}

{% block button_text %}
    Update
{% endblock %}

templates/user/user_update.html
{% extends 'user/user_form.html' %}
{% block base_title %}Update user{% endblock %}
{% block title %}
    Update user
{% endblock %}

{% block button_text %}
    Update
{% endblock %}